### ISSUE TITLE
GLIBC_2.33 missing

### ISSUE THREAD

**Issue by Niko1792** [KS3cur1ty/Lynx#1]
Hi, 
first of all - thanks for this nice piece of code :+1: 

I have problems with the encrypting/decrypting part, but that is not my my issue.

After compiling and transfer to my test machine (Ubuntu 20.04) and making it executable I get the above error when I try to run it.
GLIBC_2.31 comes with Ubuntu 20.04.

In a "real" scenario it would be not possible to ask the target to update, just to let you run the file :).

How can this issue be solved? BTW: I am a total beginner on Python - so bear with me, if some question sound "stupid"

**Comment by KS3cur1ty** [comment]
Hello !
Can you please provide more information (i.e. the machine you are compiling on) ?

**Comment by Niko1792** [comment]
I am compiling on Kali Linux 2022

**Comment by Niko1792** [comment]
Additional info: It is working on Manjaro - it comes with the needed GLIBC version. Here the execution is fine, starts, sends, but the persistence is not working. After a reboot - nothing... I hope it helps.

**Comment by KS3cur1ty** [comment]
Hmmmm ... I guess that Kali Linux 2022 uses a more recent version of GLIBC.
You can downgrade GLIBC on your Kali machine, but apparently it's a very dangerous trick, so better you compile on an older version of that distribution.

**Comment by KS3cur1ty** [comment]
Yes I know the persistence is not working fine. I am still working on it. 
The module that the keylogger uses does need a X server running, so instead of adding the script to the crontab or creating a new systemd service, you can just add it to the shell config (.bashrc/.zshrc)

**Comment by Niko1792** [comment]
ok, I will install a Kali 2021 - no problem.
I found one problem too - beside the restart is not working: when I close the terminal (I think it should run in the background - the "target" would close it, if it shows, right) - but then it stops sending too.

**Comment by Niko1792** [comment]
> .bashrc - just put my executable in this hidden folder (copy/paste)?

**Comment by KS3cur1ty** [comment]
> ok, I will install a Kali 2021 - no problem. I found one problem too - beside the restart is not working: when I close the terminal (I think it should run in the background - the "target" would close it, if it shows, right) - but then it stops sending too.

Yes, it's because the process is closed. 
Lynx is still in development, new versions will be released soon.

**Comment by KS3cur1ty** [comment]
> > .bashrc - just put my executable in this hidden folder (copy/paste)?

You can add something like : `/usr/bin/python3 /path/to/lynx.py`

**Comment by Niko1792** [comment]
so better before I play "try and fail" I wait for your new release?

Or can I help with my results / error messages from my versions how/if it works?

**Comment by KS3cur1ty** [comment]
Maybe try to deal with it, idk

**Comment by KS3cur1ty** [comment]
UPDATE:
Hey,
Persistence is now fully functional. You don't need to add a crontab entry, it will do it automatically.
